server {
    listen 80;
    server_name localhost;
    absolute_redirect off;


    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # Automatically redirect root to landing page
        if ($request_uri = "/") {
            return 301 /html/core/landing.html;
        }
    }
}
